version: "1"
services:
  api:
    build:
      dokerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    evnironment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"

  postgres:
    image: "postgres:alpine"
    restart: "always"
    ports:
      -"35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
